application: use-pyvenom
version: 0-0-0
runtime: python27
api_version: 1
threadsafe: yes
module: py

handlers:
# API SCRIPT
- url: .*
  script: app.app

# APP STATS
- url: /stats(/.*)?
  script: google.appengine.ext.appstats.ui.app
  login: admin

# LIBRARIES
libraries:
- name: webapp2
  version: "2.5.1"
- name: pycrypto
  version: "2.6"
- name: PIL
  version: "1.1.7"

builtins:
- appstats: on
- remote_api: on